// var employeeName = ['skptricks', 'sumit', 'amit', 'rakesh', 'anil'];

// // Extract array element from index-2 
// console.log(employeeName.slice(2));

// // Extract array element from index 2 and n-1 index
// console.log(employeeName.slice(2, 4));

// // Extract array element from index 1 and n-1 index
// console.log(employeeName.slice(1, 5));


// var months = ['Jan', 'Feb', 'March', 'April', 'May', 'June', 'July'];

// // removing by index
// months.splice(6);
// console.log(months)

// // removing by index and number of element
// months.splice(4, 3);
// console.log(months)
// // removing by index and number of element
// months.splice(1, 3);
// console.log(months)

